"""Verify our CPU variation implementations against flam3 ground truth.

Reads tests/flam3_reference.csv generated by tools/flam3_variation_oracle.c
and compares each variation's output against our apply_variation_cpu().

This catches bugs where both our CPU and GPU agree with each other but
disagree with flam3 (e.g. the r vs r² julian bug).
"""

from pathlib import Path

import numpy as np
import pytest

from flame_sheep.variations import apply_variation_cpu, Variation
from flame_sheep.variations._cpu import Xorshift32
import flame_sheep.variations._cpu as cpu_mod

REFERENCE_CSV = Path(__file__).resolve().parent.parent.parent / 'flam3_reference.csv'

# Map flam3 oracle var_index to our variation index
# (they should match for standard flam3 variations)
# Oracle uses our indices directly, so no mapping needed

# Default params matching the oracle's xform setup
ORACLE_PARAMS = {
    Variation.RINGS2: {'rings2_val': 0.5},
    Variation.RECTANGLES: {'rect_x': 0.8, 'rect_y': 0.6},
    Variation.NGON: {'ngon_sides': 5.0, 'ngon_power': 3.0,
                     'ngon_circle': 1.0, 'ngon_corners': 2.0},
    Variation.BENT2: {'bent2_x': 1.5, 'bent2_y': -0.5},
    Variation.BIPOLAR: {'bipolar_shift': 0.3},
    Variation.CELL: {'cell_size': 1.0},
    Variation.MODULUS_FUNC: {'modulus_x': 0.5, 'modulus_y': 0.5},
    Variation.LAZYSUSAN: {'lazysusan_x': 0.1, 'lazysusan_y': 0.1,
                          'lazysusan_spin': 0.5, 'lazysusan_twist': 0.3,
                          'lazysusan_space': 0.2},
    Variation.OSCILLOSCOPE: {'osc_separation': 1.0, 'osc_frequency': np.pi,
                             'osc_amplitude': 1.0, 'osc_damping': 0.1},
    Variation.SEPARATION: {'separation_x': 0.5, 'separation_y': 0.5,
                           'separation_xinside': 0.2, 'separation_yinside': 0.3},
    Variation.SPLIT: {'split_xsize': 0.5, 'split_ysize': 0.5},
    Variation.WHORL: {'whorl_inside': 0.5, 'whorl_outside': 0.5},
    Variation.JULIAN: {'julian_power': 4.0, 'julian_dist': 1.0},
    Variation.JULIASCOPE: {'julian_power': 4.0, 'julian_dist': 1.0},
    Variation.POLAR2: {},
    Variation.SCRY: {},
    Variation.SECANT2: {},
    Variation.LOONIE: {},
}

# Variations that use RNG — compare radius only (angle depends on seed sequence)
RNG_VARIATIONS = {Variation.JULIA, Variation.JULIAN, Variation.JULIASCOPE}

# Variations where we expect exact match
EXACT_VARIATIONS = {
    Variation.LINEAR, Variation.SINUSOIDAL, Variation.SPHERICAL,
    Variation.SWIRL, Variation.HORSESHOE, Variation.POLAR,
    Variation.BENT, Variation.FISHEYE, Variation.COSINE,
    Variation.EYEFISH, Variation.BUBBLE, Variation.RINGS2,
    Variation.RECTANGLES, Variation.NGON, Variation.SECANT2,
    Variation.LOONIE, Variation.BENT2, Variation.BIPOLAR,
    Variation.CELL, Variation.MODULUS_FUNC, Variation.OSCILLOSCOPE,
    Variation.POLAR2, Variation.SCRY, Variation.SEPARATION,
    Variation.SPLIT, Variation.WHORL, Variation.LAZYSUSAN,
}

# Map variation names to our affine for affine-reading variations
AFFINE_READING = {Variation.WAVES, Variation.POPCORN, Variation.RINGS, Variation.FAN}


def _load_reference():
    """Load flam3 reference CSV into list of (var_idx, name, x, y, ox, oy, seed)."""
    if not REFERENCE_CSV.exists():
        pytest.skip('No flam3 reference data — run: '
                    'cc -o /tmp/flam3_oracle tools/flam3_variation_oracle.c -lm && '
                    '/tmp/flam3_oracle > tests/flam3_reference.csv')
    entries = []
    with open(REFERENCE_CSV) as f:
        header = f.readline()  # skip header
        for line in f:
            line = line.strip()
            if not line or line.startswith('#'):
                continue
            parts = line.split(',')
            var_idx = int(parts[0])
            name = parts[1]
            x_in = float(parts[2])
            y_in = float(parts[3])
            # skip weight (parts[4])
            x_out = float(parts[5])
            y_out = float(parts[6])
            seed = int(parts[7])
            entries.append((var_idx, name, x_in, y_in, x_out, y_out, seed))
    return entries


@pytest.fixture(scope='module')
def reference():
    return _load_reference()


class TestFlam3OracleExact:
    """Test non-RNG variations for exact match against flam3."""

    def test_all_exact_variations(self, reference):
        mismatches = []
        for var_idx, name, x, y, ex, ey, seed in reference:
            if var_idx not in EXACT_VARIATIONS:
                continue
            if 'sheep' in name:
                continue

            params = ORACLE_PARAMS.get(var_idx, {})
            cpu_mod._current_var_params = params
            affine = None
            if var_idx in AFFINE_READING:
                affine = np.array([1, 0, 0.5, 0, 1, 0.5], dtype=np.float32)

            ox, oy = apply_variation_cpu(var_idx, x, y, 1.0, affine)

            if not (np.isfinite(ox) and np.isfinite(oy)):
                continue

            dx = abs(ox - ex)
            dy = abs(oy - ey)
            if dx > 1e-4 or dy > 1e-4:
                mismatches.append(
                    f'{name} (idx {var_idx}) at ({x},{y}): '
                    f'ours=({ox:.10f},{oy:.10f}) '
                    f'flam3=({ex:.10f},{ey:.10f}) '
                    f'diff=({dx:.2e},{dy:.2e})')

        if mismatches:
            msg = f'{len(mismatches)} mismatches:\n' + '\n'.join(mismatches[:20])
            pytest.fail(msg)


class TestFlam3OracleRadius:
    """Test RNG variations — radius should match even if angle differs."""

    def test_julian_radius(self, reference):
        mismatches = []
        for var_idx, name, x, y, ex, ey, seed in reference:
            if var_idx != Variation.JULIAN:
                continue
            if 'sheep' in name:
                params = {'julian_power': 6.0, 'julian_dist': -1.25244}
            else:
                params = {'julian_power': 4.0, 'julian_dist': 1.0}

            cpu_mod._current_var_params = params
            cpu_mod._rng = Xorshift32(seed=seed)
            ox, oy = apply_variation_cpu(var_idx, x, y, 1.0)
            cpu_mod._rng = None

            r_ours = np.sqrt(ox*ox + oy*oy)
            r_flam3 = np.sqrt(ex*ex + ey*ey)
            if abs(r_ours - r_flam3) > 1e-4:
                mismatches.append(
                    f'{name} at ({x},{y}): r_ours={r_ours:.6f} r_flam3={r_flam3:.6f}')

        if mismatches:
            pytest.fail('\n'.join(mismatches))

    def test_juliascope_radius(self, reference):
        mismatches = []
        for var_idx, name, x, y, ex, ey, seed in reference:
            if var_idx != Variation.JULIASCOPE:
                continue
            cpu_mod._current_var_params = {'julian_power': 4.0, 'julian_dist': 1.0}
            cpu_mod._rng = Xorshift32(seed=seed)
            ox, oy = apply_variation_cpu(var_idx, x, y, 1.0)
            cpu_mod._rng = None

            r_ours = np.sqrt(ox*ox + oy*oy)
            r_flam3 = np.sqrt(ex*ex + ey*ey)
            if abs(r_ours - r_flam3) > 1e-4:
                mismatches.append(
                    f'{name} at ({x},{y}): r_ours={r_ours:.6f} r_flam3={r_flam3:.6f}')

        if mismatches:
            pytest.fail('\n'.join(mismatches))


class TestMathInvariants:
    """Test mathematical properties that must hold regardless of implementation."""

    def test_spherical_is_involution(self):
        """spherical(spherical(p)) ≈ p (for weight=1)."""
        for x, y in [(1.0, 0.5), (-0.3, 0.7), (2.0, 1.0)]:
            x1, y1 = apply_variation_cpu(Variation.SPHERICAL, x, y, 1.0)
            x2, y2 = apply_variation_cpu(Variation.SPHERICAL, x1, y1, 1.0)
            np.testing.assert_allclose([x2, y2], [x, y], atol=1e-6,
                err_msg=f'spherical not involution at ({x},{y})')

    def test_linear_is_identity(self):
        """linear(p) = p."""
        for x, y in [(1.0, 0.5), (-0.3, 0.7)]:
            ox, oy = apply_variation_cpu(Variation.LINEAR, x, y, 1.0)
            assert ox == pytest.approx(x) and oy == pytest.approx(y)

    def test_sinusoidal_at_zero(self):
        """sin(0) = 0."""
        ox, oy = apply_variation_cpu(Variation.SINUSOIDAL, 0.0, 0.0, 1.0)
        assert abs(ox) < 1e-10 and abs(oy) < 1e-10

    def test_sinusoidal_at_pi_half(self):
        """sin(π/2) = 1."""
        ox, oy = apply_variation_cpu(Variation.SINUSOIDAL, np.pi/2, 0.0, 1.0)
        assert ox == pytest.approx(1.0, abs=1e-6)

    def test_exponential_at_zero(self):
        """exp(0) should give specific value (flam3 exponential uses x-1)."""
        # exponential: e^(x-1) * (cos(πy), sin(πy))
        # At (0,0): e^(-1) * (1, 0) ≈ (0.3679, 0)
        ox, oy = apply_variation_cpu(Variation.EXPONENTIAL, 0.0, 0.0, 1.0)
        assert ox == pytest.approx(np.exp(-1), abs=1e-4)
        assert abs(oy) < 1e-6

    def test_exp_func_at_zero(self):
        """Complex exp at (0,0): e^0 * (cos(0), sin(0)) = (1, 0)."""
        ox, oy = apply_variation_cpu(Variation.EXP_FUNC, 0.0, 0.0, 1.0)
        assert ox == pytest.approx(1.0, abs=1e-6)
        assert abs(oy) < 1e-6

    def test_log_exp_roundtrip(self):
        """log(exp(z)) ≈ z for complex exp/log."""
        for x, y in [(0.5, 0.3), (1.0, -0.5)]:
            ex, ey = apply_variation_cpu(Variation.EXP_FUNC, x, y, 1.0)
            lx, ly = apply_variation_cpu(Variation.LOG_FUNC, ex, ey, 1.0)
            np.testing.assert_allclose([lx, ly], [x, y], atol=1e-4,
                err_msg=f'log(exp(z)) != z at ({x},{y})')

    def test_sin_cos_pythagorean(self):
        """sin²(z) + cos²(z) should... not equal 1 for complex args.
        But sin(x,0) = (sin(x), 0) and cos(x,0) = (cos(x), 0)."""
        x = 0.7
        sx, sy = apply_variation_cpu(Variation.SIN_FUNC, x, 0.0, 1.0)
        cx, cy = apply_variation_cpu(Variation.COS_FUNC, x, 0.0, 1.0)
        assert sx == pytest.approx(np.sin(x), abs=1e-6)
        assert cx == pytest.approx(np.cos(x), abs=1e-6)
        assert abs(sy) < 1e-6
        assert abs(cy) < 1e-6

    def test_bent_positive_unchanged(self):
        """bent leaves positive x,y unchanged."""
        ox, oy = apply_variation_cpu(Variation.BENT, 1.0, 1.0, 1.0)
        assert ox == pytest.approx(1.0)
        assert oy == pytest.approx(1.0)

    def test_bent_negative_x_doubles(self):
        """bent doubles negative x."""
        ox, oy = apply_variation_cpu(Variation.BENT, -1.0, 1.0, 1.0)
        assert ox == pytest.approx(-2.0)
        assert oy == pytest.approx(1.0)

    def test_bent_negative_y_halves(self):
        """bent halves negative y."""
        ox, oy = apply_variation_cpu(Variation.BENT, 1.0, -1.0, 1.0)
        assert ox == pytest.approx(1.0)
        assert oy == pytest.approx(-0.5)

    def test_julian_output_count(self):
        """julian(power=N) should produce N distinct output angles from the same point."""
        cpu_mod._current_var_params = {'julian_power': 6.0, 'julian_dist': 1.0}
        angles = set()
        for seed in range(10000):
            # Use larger spread of seeds to ensure RNG diversity
            cpu_mod._rng = Xorshift32(seed=seed * 7919 + 1)
            ox, oy = apply_variation_cpu(Variation.JULIAN, 1.0, 0.5, 1.0)
            cpu_mod._rng = None
            angle = round(np.arctan2(oy, ox), 1)
            angles.add(angle)
        # Should have exactly 6 distinct angles (power=6)
        assert len(angles) == 6, f'Expected 6 angles, got {len(angles)}: {sorted(angles)}'

    def test_disk_uses_flam3_theta(self):
        """disk uses atan(x,y) not atan(y,x) — flam3 convention."""
        # At (1, 0): atan(x,y) = atan(1,0) = π/2, atan(y,x) = atan(0,1) = 0
        # disk: (θ/π) * (sin(πr), cos(πr))
        # With atan(x,y): θ = π/2, so factor = 0.5
        # With atan(y,x): θ = 0, so factor = 0
        ox, oy = apply_variation_cpu(Variation.DISK, 1.0, 0.0, 1.0)
        # If using correct atan(x,y), output should be nonzero
        assert abs(ox) > 0.1 or abs(oy) > 0.1, \
            f'disk at (1,0) gave ({ox},{oy}) — may be using wrong atan convention'
